accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 1000
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_path: !!python/object/apply:pathlib.PosixPath
- /
- home
- adrien
- deep-traffic-generation
- deep_traffic_generation
- data
- denoised_v3.pkl
default_root_dir: null
deterministic: false
dilation_base: 2
distributed_backend: null
dropout: 0.0
early_stop: false
fast_dev_run: false
features:
- track_unwrapped
- groundspeed
- altitude
- timedelta
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
h_dims:
- 16
- 16
- 16
init_features:
- latitude
- longitude
kernel_size: 16
label: null
latent_dim: 16
learning_rate: 0.001
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 100
max_steps: null
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
network_name: tc_gan
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
sampling_factor: 10
show_latent: false
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
test_batch_size: null
tpu_cores: null
track_grad_norm: -1
train_ratio: 1.0
truncated_bptt_steps: null
val_check_interval: 1.0
val_ratio: 0.0
weights_save_path: null
weights_summary: top
